### ISSUE TITLE
Does this work with putty? 

### ISSUE THREAD

**Issue by Remonli** [rupor-github/wsl-ssh-agent#13]
Hi, 

I want to use putty as ssh client and windows openssh agent as key agent instead of pageant
from putty, but I found it does not work at all.

After I use windows 10 (1909) ssh-add loading my private key , putty still ask for a password, 
seems it doesn't find windows key agent service. 

Would this wsl-ssh-agent help ? 
thanks.

**Comment by rupor-github** [comment]
I do not think so - as far as I know putty talks only with pageant using has very different interface - shared memory rather than domain socket.
