### ISSUE TITLE
It is compatible with gpg-connect-agent?

### ISSUE THREAD

**Issue by LucaZulberti** [rupor-github/wsl-ssh-agent#15]
I run `source ~/.bashrc` containing:
```
SSHDIR="${HOME}/.ssh"
WINWSLDIR="/mnt/c/WSL"
NPIPERELAY="${WINWSLDIR}/bin/npiperelay.exe"

SSH_AUTH_SOCK="${SSHDIR}/ssh-agent.sock"

ss -a | grep -q $SSH_AUTH_SOCK
if [ $? -ne 0 ]; then
    rm -f $SSH_AUTH_SOCK
    ( setsid socat UNIX-LISTEN:$SSH_AUTH_SOCK,fork EXEC:"${NPIPERELAY} -ei -s //./pipe/openssh-ssh-agent",nofork & )
fi
````

then `ssh-add -l`:
```
2020/05/28 20:15:21 open //./pipe/openssh-ssh-agent: The system cannot find the file specified.
error fetching identities: communication with agent failed
```

**Comment by rupor-github** [comment]
I do not think your question is related to this project in any possible way, sorry - my understanding is that you are probably looking to communicate with `gpg-agent` which on Windows (I am guessing here) is implementing Cygwin UNIX Socket to make itself available to `gpg-connect-agent`. Where npiperelay.exe comes into play I have no idea, but you may try looking at [original project](https://github.com/jstarks/npiperelay).

**Comment by LucaZulberti** [comment]
I have all things correctly setup on windows. I can use the keys I have on the smartcard.
The fact is I'm not using OpenSSH but GPG SSH Agent.
Is the pipe //./pipe/openssh-ssh-agent generated by your tool compatible only with OpenSSH agent?

(I don't know very well how these things really work, I'm supposing this can be the reason I'm facing this issue.)

**Comment by rupor-github** [comment]
@LucaZulberti  - https://github.com/rupor-github/win-gpg-agent

**Comment by LucaZulberti** [comment]
Thank you so much, it works!
