### ISSUE TITLE
README needs a tweak for WSL2 

### ISSUE THREAD

**Issue by musm** [rupor-github/wsl-ssh-agent#16]
In https://github.com/rupor-github/wsl-ssh-agent#wsl-2-compatibility

The path for `npiperelay.exe` needs to be on a Windows partition as mentioned. However in the `.bashrc` snippet attached,  it has the following WSL path  `npiperelay.exe`, since `$HOME` refers to the  WSL 2 user folder.

`$HOME/winhome/.wsl/npiperelay.exe`

The way I managed to get this to work is extract the binaries provided in this repo to say `C:\TMP\npiprelay.exe`

**Comment by rupor-github** [comment]
This is just an example....
![example011](https://user-images.githubusercontent.com/5368784/85224247-e06e1b00-b396-11ea-9600-7ffc6b272cbc.jpg)

**Comment by ashnur** [comment]
It might be obvious for someone who is not very new to wsl, but I also had to search for winhome in this repo to be sure, when a simple bracketing like `<windows user home directory>` or `${you win user home dir}` would make it clear. Although, maybe there would be still people asking questions :)  Naming is hard, but abbreviating the name when it is actually just an example is too abstract in any books.

**Comment by rupor-github** [comment]
I tried to improve documentation a bit  :) In a future if you have a suggestion on how to make it more readable - simply submit a PR 😄

**Comment by ashnur** [comment]
Thanks, I will keep it in mind :)
