### ISSUE TITLE
Hide systray icon

### ISSUE THREAD

**Issue by michel-m** [rupor-github/wsl-ssh-agent#17]
Hey,
Thanks for this great tool!
Is there a way to hide the tray icon? I'd like to have it running in the background at startup without cluttering the taskbar.
Thanks in advance for your answer.

**Comment by rupor-github** [comment]
Hi. This is "proper" Windows tray notification icon application, you could visit Windows Taskbar settings, click "Select which icons appear on the taskbar" and unclutter your taskbar as it was intended by Windows UI designers 😄
