### ISSUE TITLE
WSL2 npiperelay.exe path length limit

### ISSUE THREAD

**Issue by ksurl** [rupor-github/wsl-ssh-agent#19]
followed the directions for WSL2 and it keeps saying error communicating with agent. the only difference was that my location of the exe was in `%localappdata%\Programs\wsl-ssh-agent`. moved it to `%userprofile%\.wsl` and it works fine after restarting WSL2. the path is fully expanded in the .bashrc file i.e. `/mnt/c/Users/$USER/AppData/Local/Programs/wsl-ssh-agent` vs `/mnt/c/Users/$USER/.wsl`

**Comment by rupor-github** [comment]
npiperelay.exe is a separate project , I have no intention of taking over 😄 If you think that something needs fixing there (or could be improved) - it probably make sense to communicate there.... Having said all this - it uses golang.org/x/sys/windows to access CreateFile and other Windows APIs...
