### ISSUE TITLE
SSH_AUTH_SOCK causes ssh-agent stop working on Windows side

### ISSUE THREAD

**Issue by GethDeeo** [rupor-github/wsl-ssh-agent#2]
Hi,

I'm using wsl-ssh-agent since hours after its first release, great stuff!

At first, I've tried the "-setenv" option and I thought it's very nice, I hadn't have to do anything on WSL side, it's just worked.
Not long after that I've realized that as long as SSH_AUTH_SOCK is set, I cannot use the agent on Windows side.

Windows 10 Pro (18362.356)
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
wsl-ssh-agent 1.2.1

    D:\ssh-add -l
    error fetching identities: invalid format

    D:\ssh -vvv somewhere
    ...
    debug3: failed to open file:D:/dev/tty error:3
    debug1: read_passphrase: can't open /dev/tty: No such file or directory
    Enter passphrase for key 'C:\Users\someuser/.ssh/id_something_ed25519':

After unsetting the environment variable at least in current session, it's working as usual.

As a workaround I'm specifying explicitly the path to the socket using "-socket" option, and manually exporting the SSH_AUTH_SOCK variable on WSL side with the corresponding path.

Anyway, it's not really a big issue, I'm just curious: is it happening only on my systems or it's a known limitation (not wsl-ssh-agent's, moreso OpenSSH's in Windows)?

**Comment by rupor-github** [comment]
It is a known limitation, I will document it. Looking at [openssh code](https://github.com/PowerShell/openssh-portable) in `win32compat\wmain_common.c`:

```
	if (getenv("SSH_AUTH_SOCK") == NULL)
		_putenv("SSH_AUTH_SOCK=\\\\.\\pipe\\openssh-ssh-agent");
```
I guess it says it all

**Comment by rupor-github** [comment]
@GethDeeo - please, see latest release. You could now specify environment variable name to be translated to WSL side. Hope you will find it useful.
