### ISSUE TITLE
Lockfile cannot be created

### ISSUE THREAD

**Issue by ArcticXWolf** [rupor-github/wsl-ssh-agent#20]
Hello,

I got the problem that the application wont start for me, except I run it in admin mode. But this is problematic, because then I cannot put it into autostart. I did a bit of debugging and this is the debugview output:

```
[16160] [wsl-ssh-agent-gui] Windows - CurrentMajorVersionNumber: 10, CurrentBuild: 18363
[16160] [wsl-ssh-agent-gui] Application already running
```

But the lock-file wasnt there. I then took ProcMon to view File accesses and you can see:
```
21:16:31,1798246	wsl-ssh-agent.exe	8816	CreateFile	C:\Users\MYUSERNAME\AppData\Local\Temp\wsl-ssh-agent-gui.lock	NAME NOT FOUND	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
21:16:31,1800598	wsl-ssh-agent.exe	8816	CreateFile	C:\Users\MYUSERNAME\AppData\Local\Temp\wsl-ssh-agent-gui.lock	NAME NOT FOUND	Desired Access: Read Attributes, Synchronize, Disposition: Open, Options: Synchronous IO Non-Alert, Attributes: n/a, ShareMode: None, AllocationSize: n/a
21:16:31,1803939	wsl-ssh-agent.exe	8816	CreateFile	C:\Users\MYUSERNAME\AppData\Local\Temp\wsl-ssh-agent-gui.lock	ACCESS DENIED	Desired Access: Generic Write, Read Attributes, Disposition: Create, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: 0
21:16:31,1807090	wsl-ssh-agent.exe	8816	CreateFile	C:\Users\MYUSERNAME\AppData\Local\Temp\wsl-ssh-agent-gui.lock	NAME NOT FOUND	Desired Access: Read Data/List Directory, Synchronize, Disposition: Open, Options: Directory, Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
```

As you can see in Line 3 (Lines 1,2 and 4 are just checks from your application, if the file is already there), it gets AccessDenied on creation of the lockfile. But the permissions are all correct:

```
PS C:\Users\MYUSERNAME\AppData\Local\Temp> Get-Acl | Format-List


Path   : Microsoft.PowerShell.Core\FileSystem::C:\Users\MYUSERNAME\AppData\Local\Temp
Owner  : MYPC\MYUSERNAME
Group  : NT-AUTORITÄT\SYSTEM
Access : NT-AUTORITÄT\SYSTEM Allow  FullControl
         VORDEFINIERT\Administratoren Allow  FullControl
         MYPC\MYUSERNAME Allow  FullControl
Audit  :
Sddl   : O:S-1-5-21-1011926168-4098507291-4013957409-1000G:SYD:(A;OICIID;FA;;;SY)(A;OICIID;FA;;;BA)(A;OICIID;FA;;;S-1-5
         -21-1011926168-4098507291-4013957409-1000)
```

The process also runs under the correct user MYUSERNAME.

Sadly I have no idea how to debug this further... Any suggestions?

**Comment by rupor-github** [comment]
Honestly I have no idea, short of usual - do you have an antivirus? could you turn it off and try again? I know it is laughable. 

Here are a couple of questions/suggestions:
- Does it run when you simply start wsl-ssh-agent from command line? How procmon output compares to the "bad" case?
- I do start wsl-ssh-agent from "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Run", did not use STARTUP folder for a while - do you need .lnk run from it? Could it be wrong?
- I think your owner/group for temp directory is strange - how come group is NT-AUTORITÄT\SYSTEM? This is temp directory - it should be wide open. In my case I have Owner  : COMPRUPOR\rupor, Group  : COMPRUPOR\rupor. Resulting sddl looks completly different from what I have. Do you mind renaming your temp directory, creating new one under proper account, rebooting and trying again?

All in all I do think you have something controlling your local environment - it may not be antivirus, but it does not look clean to me.

**Comment by ArcticXWolf** [comment]
Thanks for the fast reply.

Sadly none of your suggestions have been the issue.

- It is the same issue with the commandline. Administrative command line works, normal user not.
- The lnk is correct (but this is confirmed by having the same problem in the commandline).
- You are right the owner group is strange, I changed it. Now the sddls should be everything owned by my account and full access for all:

```
PS C:\Users\MYUSERNAME\AppData\Local\Temp> Get-Acl | Format-List


Path   : Microsoft.PowerShell.Core\FileSystem::C:\Users\MYUSERNAME\AppData\Local\Temp
Owner  : MYPC\MYUSERNAME
Group  : MYPC\MYUSERNAME
Access : NT-AUTORITÄT\SYSTEM Allow  FullControl
         VORDEFINIERT\Administratoren Allow  FullControl
         MYPC\MYUSERNAMEAllow  FullControl
Audit  :
Sddl   : O:S-1-5-21-1011926168-4098507291-4013957409-1000G:S-1-5-21-1011926168-4098507291-4013957409-1000D:AI(A;OICIID;
         FA;;;SY)(A;OICIID;FA;;;BA)(A;OICIID;FA;;;S-1-5-21-1011926168-4098507291-4013957409-1000)
```

- Concerning Antivirus I only have the Windows-builtin Defender, but it did not block anything.

I agree that this probably is not a problem of the wsl-ssh-agent, but i really have no further idea :(

**Comment by rupor-github** [comment]
Well, the only thing I could say is: user should be able to lauch wsl-ssh-agent from command line without a problem. If it could not - you probably have bigger problems than running agent :) It looks like normal non-privileged user cannot create file in the its own temp directory. Did you try to launch .exe directly, without .lnk file?

Simple steps to validate this would be to create c:\temp, set all environment variables accordingly and attempt to launch from command prompt.

 At this point (not my turf, you are on your own, I am just throwing stuff at the wall) I would in no particular order:

1. Check if file system where temp is located has some free space
2. Check that temp directory does not have read-only attribute set
3. Try to see if fiddling with UAC level changes anything.
4. You did not tell if you are running antivirus - may be setting an exception there?
5. Windows Integrity Level and icacls.exe - old installations of firefox used too play with it, not sure if this could create such situation.
6. Create different (new) user account login with it and see if it works.

**Comment by ArcticXWolf** [comment]
No luck, all the suggestions do not work.
I performed all tests with TEMP directed at a different drive (E:\) where I have full access and ownership. Also I disabled the Windows Defender as far as I was able to (concerning your question of antivirus).

However I cloned your project and inserted some debugging statements:
```
diff --git a/gui.go b/gui.go
index c3d65c7..7d62bf1 100644
--- a/gui.go
+++ b/gui.go
@@ -336,11 +336,19 @@ func main() {
                os.Exit(1)
        }

+  info, err := os.Stat(os.TempDir())
+  log.Print(info)
+  log.Print(info.Mode())
+  log.Print(info.Mode().Perm())
+  log.Print(err)
+
+
        // Only allow single instance to run
        lockName := filepath.Join(os.TempDir(), title+".lock")
        inst, err := si.CreateLockFile(lockName)
        if err != nil {
                log.Print("Application already running")
+               log.Print(err)
                os.Exit(0)
        }
        defer func() {
```

Which gives this output:
```
[10572] [wsl-ssh-agent-gui] Windows - CurrentMajorVersionNumber: 10, CurrentBuild: 19041
[10572] [wsl-ssh-agent-gui] &{\ 22 {4159984094 30245582} {2579067679 30839490} {1483125622 30839460} 0 16384 0 0 {0 0} E:\ 0 0 0 false}
[10572] [wsl-ssh-agent-gui] drwxrwxrwx
[10572] [wsl-ssh-agent-gui] -rwxrwxrwx
[10572] [wsl-ssh-agent-gui] <nil>
[10572] [wsl-ssh-agent-gui] Application already running
[10572] [wsl-ssh-agent-gui] open E:\wsl-ssh-agent-gui.lock: Access is denied.
```

As you see in Line 3-5 there is no error in OS.Stat and the permissions it reads are FullAccess. Shouldn't the application be able to create files there now?

I even disabled the lock-functionality, but then the application cannot create files later either (for example the socket).

It is very weird..

**Comment by rupor-github** [comment]
Only thing I could say is that lock file always has the same name: wsl-ssh-agent-gui.lock. If by some bad luck some time ago it was created with wrong ownership or you somehow are starting several instances of the program (not sure how it is possible, but)  program would not be able to do anything with it and will fail to start. However your procmon trace clearly states that it is single instance of wsl-ssh-agent.exe. Here is mine, for comparison, just in case:

```
7:18:10.3185686 PM	wsl-ssh-agent-gui.exe	8540	CreateFile	C:\Users\rupor\AppData\Local\Temp\wsl-ssh-agent-gui.lock	NAME NOT FOUND	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
7:18:10.3186347 PM	wsl-ssh-agent-gui.exe	8540	CreateFile	C:\Users\rupor\AppData\Local\Temp\wsl-ssh-agent-gui.lock	NAME NOT FOUND	Desired Access: Read Attributes, Synchronize, Disposition: Open, Options: Synchronous IO Non-Alert, Attributes: n/a, ShareMode: None, AllocationSize: n/a
7:18:10.3186997 PM	wsl-ssh-agent-gui.exe	8540	CreateFile	C:\Users\rupor\AppData\Local\Temp\wsl-ssh-agent-gui.lock	SUCCESS	Desired Access: Generic Write, Read Attributes, Disposition: Create, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: 0, OpenResult: Created
7:18:10.3188475 PM	wsl-ssh-agent-gui.exe	8540	WriteFile	C:\Users\rupor\AppData\Local\Temp\wsl-ssh-agent-gui.lock	SUCCESS	Offset: 0, Length: 4, Priority: Normal
```

What is happening reminds me old days of anti-virus when AV will keep important file open for a while after program creates it for inspection. Can you may be go to "virus and threat protections" and add a specific "process" exception for wsl-ssh-agent? Short of that - I am out of ideas....

**Comment by ArcticXWolf** [comment]
WOW. I got the solution. Thank you very much, your tip about the icacls helped me to go in the right direction.

Writing up the solution in the case that someone else has the same problem:
In a last try I turned on file object auditing (GroupPolicyEditor->Computer->Windows->>Security->Local->Audit Policy->Audit object access) and enabled that on my TEMP folder. I was hoping to get a reason WHY the executable is denied access.

Afterwards I got the following event in my event viewer:
```
...
Object:
	Object Server:		Security
	Object Type:		File
	Object Name:		C:\Users\MYUSER\AppData\Local\Temp\wsl-ssh-agent-gui.lock
	Handle ID:		0x0
	Resource Attributes:	-

Process Information:
	Process ID:		0x2edc
	Process Name:		C:\Program Files\WSLSSHAgent\wsl-ssh-agent-gui.exe

Access Request Information:
	Transaction ID:		{00000000-0000-0000-0000-000000000000}
	Accesses:		READ_CONTROL
				SYNCHRONIZE
				WriteData (or AddFile)
				AppendData (or AddSubdirectory or CreatePipeInstance)
				WriteEA
				ReadAttributes
				WriteAttributes
				
	Access Reasons:		READ_CONTROL:	Unknown or unchecked
				SYNCHRONIZE:	Unknown or unchecked
				WriteData (or AddFile):	Denied by Integrity Policy check
				AppendData (or AddSubdirectory or CreatePipeInstance):	Unknown or unchecked
				WriteEA:	Unknown or unchecked
				ReadAttributes:	Unknown or unchecked
				WriteAttributes:	Unknown or unchecked
...
```

The important bit is in access reasons: **Denied by Integrity Policy check**
This (together with your tip before) led me to check the icacls again of the executable (sorry it is in german):

```
PS C:\Program Files\WSLSSHAgent> icacls .\wsl-ssh-agent-gui.exe
.\wsl-ssh-agent-gui.exe NT-AUTORITÄT\SYSTEM:(F)
                    VORDEFINIERT\Administratoren:(F)
                    MYPC\MYUSER:(F)
                    NT-AUTORITÄT\SYSTEM:(I)(F)
                    VORDEFINIERT\Administratoren:(I)(F)
                    VORDEFINIERT\Benutzer:(I)(RX)
                    MYPC\MYUSER:(I)(F)
                    ZERTIFIZIERUNGSSTELLE FÜR ANWENDUNGSPAKETE\ALLE ANWENDUNGSPAKETE:(I)(RX)
                    ZERTIFIZIERUNGSSTELLE FÜR ANWENDUNGSPAKETE\ALLE EINGESCHRÄNKTEN ANWENDUNGSPAKETE:(I)(RX)
                    Verbindliche Beschriftung\Niedrige Verbindlichkeitsstufe:(I)(NW)
```

The last line is the problem, the executable has the low integrity level set which disallows access to most of the files everywhere. This is strange, as I never set any of this on that exe. And by checking the integrity levels on all folders in the parent directory tree I found that **my system drive (and all drives) have their integrity level set to low**. This lets executables spawn with the same level. The fix is simple:

```
icacls C: /setintegritylevel medium
```
And everything works. Apparently this wrong setting can happen if you upgraded to windows 10 from windows 7, new installations do not have this problem. This explains why creating new users did not help, but I never had this problem on my notebook (it was a new installation).

Still I do not know why other executables from the internet never had any problems.. Maybe they set their integrity level in their manifest or so? At least I learned new things about windows: how to debug file accesses via file auditing and that there are more file security options (i.e. the integrity levels) apart from just the permission.

Thanks again for your ideas even when my problem was clearly not an issue of your program. I was just clueless where to search further ^^
