### ISSUE TITLE
Release archive using ZIP instead of 7zip

### ISSUE THREAD

**Issue by Morgy93** [rupor-github/wsl-ssh-agent#22]
Hello,

since the release is mainly a Windows application and 7-ZIP is not natively supported on Windows it would be great to offer ZIP download (like the source code release) which is natively supported on Windows.
Otherwise, you first have to download and install external software only to use your software.

**Comment by rupor-github** [comment]
This is a bit strange - but I'll oblige starting with 1.5.1
