### ISSUE TITLE
Why "gpg" in file name?

### ISSUE THREAD

**Issue by strarsis** [rupor-github/wsl-ssh-agent#23]
@rupor-github: In the latest release ([v1.5.1](https://github.com/rupor-github/wsl-ssh-agent/releases/tag/v1.5.1)) the file name (when ignoring the file extension and format) is now `wsl-gpg-agent` instead of `wsl-ssh-agent`. Does this new filename indicate newly added GPG support? Or is this a typo?

**Comment by rupor-github** [comment]
This is a typo in archive name, I will reissue. Support for gpg indeed is available - but in different project of mine: win-gpg-agent.

**Comment by rupor-github** [comment]
Fixed in 1.5.2

**Comment by strarsis** [comment]
@rupor-github: Yes, GPG would be a great addition :)

**Comment by rupor-github** [comment]
Switch to https://github.com/rupor-github/win-gpg-agent - there is no loss in functionality
