### ISSUE TITLE
Feature request: disable clipboard server?

### ISSUE THREAD

**Issue by 0xabu** [rupor-github/wsl-ssh-agent#26]
Could we have a way to disable the clipboard functionality? From quick code inspection it seems to do nothing unless `~/.gclpr` exists, but I'd be more comfortable (from a security paranoia standpoint) knowing that it was explicitly disabled.

**Comment by rupor-github** [comment]
If there are no keys available in the configuration file clipboard integration is disabled:

```
if len(pkeys) > 0 {
		// we have possible clients for remote clipboard
		clipHelp = fmt.Sprintf("gclpr is serving %d key(s) on port %d", len(pkeys), clipPort)
```
