### ISSUE TITLE
Pass name of process?

### ISSUE THREAD

**Issue by strarsis** [rupor-github/wsl-ssh-agent#28]
Would it be possible to pass the name of the process requesting the keys?
Currently `npiperelay` is shown in the tray by KeeAgent plugin/KeePass.
It would be nice if the underlying process is shown, e.g. `ssh` or `sftp`.

**Comment by rupor-github** [comment]
I am not aware of any "standard" well defined mechanism to share such information between ssh-agent server and client: [SSH Agent Protocol](https://tools.ietf.org/id/draft-miller-ssh-agent-01.html). If it is implemented directly in KeePass or KeeAgent - then this question should be addressed to the authors. If some of the ssh-agent protocol's fileds are used unconventionally (for example comment/extension fields) - I need to see documentation and will look into possibility of adding such support. In other words - I need to know how it is done presently. I do not have any expertise using KeePass and have no need for it myself.

**Comment by strarsis** [comment]
KeeAgent uses the process name that requested the key:
https://github.com/dlech/KeeAgent/blob/3caecd7ff40a3a282e51a61f4e8fdbbf7f093be2/KeeAgent/KeeAgentExt.cs#L853
There seems to be currently no parameter for passing a custom/proxy name.
Related: https://github.com/dlech/KeeAgent/issues/327

**Comment by rupor-github** [comment]
I looked at the `dlech/SshAgentLib` code - as I suspected the only case knowledge of the process is available is the Pageant case where `otherProcess = WinInternals.FindProcessWithMatchingHandle(fileMap);` Windows (and Pageant) specific call is made in PageantAgent. Process always empty for UnixAgent. Not sure if requested extension to ssh-agent protocol is feasible and if it is how secure it will be to pass process name around. I am going to close this as I purely do not have either resources or necessity to push it through. If situation changes - please, feel free to reopen this.
