### ISSUE TITLE
"communication with agent failed" when trying to connect using SSH in Arch (WSL 2)

### ISSUE THREAD

**Issue by brw** [rupor-github/wsl-ssh-agent#29]
Hi! Not sure if I should report this issue here, but I figured you might be able to help me further at least.

For some reason wsl-ssh-agent doesn't seem to work (or well, only partially works) under Arch (either installed through https://github.com/nullpo-head/wsl-distrod or https://github.com/yuk7/ArchWSL). If I run `ssh-add -l` it connects to the ssh-agent just fine and lists my keys, but when I actually try to SSH somewhere it still asks me for my passphrase and I see this in the verbose log:
```
debug2: get_agent_identities: ssh_agent_bind_hostkey: communication with agent failed
debug1: get_agent_identities: ssh_fetch_identitylist: communication with agent failed
```
It "just works" in Ubuntu WSL environments (both through Microsoft Store and through https://github.com/nullpo-head/wsl-distrod), but the exact same setup does not seem to work under Arch.

Let me know if you need any more info from me, I'm not sure what exactly I should supply. And apologies if this setup is unsupported, feel free to close the issue if that's the case. I just figured since this doesn't seem to be Distrod or ArchWSL specific but rather distro-specific I might as well start by asking here.

**Comment by rupor-github** [comment]
It looks to me that for whatever reason you have actual ssh-agent starting and running in your Arch WSL2. Looks like when you are doing `ssh-add -L` you are actually connecting to one SSH_AUTH socket and when using actual ssh - to another, hence the messages...

**Comment by brw** [comment]
That's strange, I'm not actually starting ssh-agent anywhere, nor do I see it running in `ps` or `htop`, not while connecting with SSH either. I actually see `/tools/init /mnt/c/Users/Bas/wsl-ssh-agent/npiperelay.exe -ei -s //./pipe/openssh-ssh-agent` being executed for a split second when I try to connect using ssh, which I assume is what's to be expected (since the same thing happens on Ubuntu WSL2). I think that shows that it's trying to connect to the correct SSH_AUTH socket?

**Comment by rupor-github** [comment]
You are probably right, except split second may not be a good definition for the event. You could try to continue tracing on Windows side by running gui with -d switch and using DbgView to capture the trace. I did not try Arch in WSL2, but I used multiple versions of Ubuntu and Alpine without a problem. Would love to hear your story since Arch is not on my WSL2 radar at the moment (and I switched to win-gpg-agent long time ago) 😄 Could it be that Arch is using newer version of SSH protocol? Did you update you openssh on Windows side to the latest version (8.6p1)?

**Comment by brw** [comment]
Ah you're correct, it seems to be a version mismatch. Perhaps a newer version of the SSH protocol yea. Arch is on openssh-8.9p1 while Windows is indeed on 8.6p1. Downgrading to 8.8p1 on Arch actually fixes it. It just doesn't work anymore since 8.9p1.

Of course it's not recommended to downgrade packages on a rolling release distro, but I suppose this will do for now. Thanks!

**Comment by rupor-github** [comment]
It may be possible to change something in ssh client configuration to enable backward compatibility - not my area but may be worth exploring before downgrade.

**Comment by brw** [comment]
It appears that there were some ssh-agent protocol extensions added in 8.9, see https://www.openssh.com/agent-restrict.html.

> The most immediate practical consideration is that this feature requires protocol extensions in ssh-agent, ssh-add, ssh and sshd for most participating hosts. The requirement to run an updated ssh-agent, ssh and ssh-add is fairly obvious (older versions simply don't support the feature)

Maybe it's not directly related but it's the most obvious thing I can find. It's probably expected that ssh, ssh-agent, and ssh-add are all upgraded at the same time (which is usually the case of course). ssh-add still connects just fine though, but I assume it's easier to break backward compatibility for ssh and not ssh-add.

Looking through the ssh_config man page I can't really find any options that would enable some sort of backward compatibility.

**Comment by brookst** [comment]
I ran into this with Ubuntu 22.04 and had to update OpenSSH on the Windows host to get things working.
Windows ships an old version as a 'Windows feature':
```
PS > ssh -V
OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
```
I have scoop installed, so I uninstalled the old version and ran:
```
PS > scoop install openssh
Installing 'openssh' (8.9.1.0p1) [64bit]...

PS > ssh -V
OpenSSH_for_Windows_8.9p1, LibreSSL 3.4.3
```
ssh inside WSL could then access keys through the Windows ssh-agent as before.

**Comment by rupor-github** [comment]
Or simply download latest release from https://github.com/PowerShell/Win32-OpenSSH and copy it on top of "Windows feature" in %SystemRoot%\System32\OpenSSH overwriting what was installed. This way it will be much easier if you ever need to run "sshd" under different users.

**Comment by brookst** [comment]
That repo only seems to have the source code. This one has builds: https://github.com/PowerShell/Win32-OpenSSH/releases/ however I tried the MSI installer and it didn't seem to work properly (perhaps it uses a different path and needs to amend the $env:PATH). In any case the scoop package definitely works and was hassle free.

**Comment by rupor-github** [comment]
Not the msi installer - I copy proper zip and unpack on top of "Windows Feature" files. MSI only become available in the last release. I do that copy with each new release (started long time ago). Needed to run FixHostFilePermissions.ps1 and FixUserFilePermissions.ps1 once.
