### ISSUE TITLE
Is this compatible with WSL 2?

### ISSUE THREAD

**Issue by wizonesolutions** [rupor-github/wsl-ssh-agent#3]

**Comment by rupor-github** [comment]
I have no WSL2 to try, but from what I read I do not see why not. may be you could tell us 😄?

**Comment by cHolzberger** [comment]
Unix Sockets passthrough not supported on WSL for now...

**Comment by rupor-github** [comment]
Well, let's wait and see - as far as I know WSL 2 should be part of 20H1 release, which is half a year away at this point.

**Comment by SirHenryIII** [comment]
WSL-2 is part of the next release somewhere in November. I have just installed the release candidate and start playing with it. You can easily switch between WSL-1 and 2 for each distro you have installed. But right now it's not working for any version.

Use this command to switch between WSL-1 and 2 and replace debian with the distro you are using:
 `wsl --set-version debian 1`

Both WSL_AUTH_SOCK and SSH_AUTH_SOCK are populated to my session and is pointing to the correct file. Not sure how to test the SOCK file...

**Comment by rupor-github** [comment]
I think if you run `ssh-add -l` in WSL 2 session and see the list of your identities - it works....

**Comment by mackncheesiest** [comment]
fwiw, I seem to be having issues with WSL V2. 
Decided to try out Ubuntu+WSL V2 and `ssh-add -L` doesn't list identities 
But it still does in Ubuntu+WSL V1

Verified that `$SSH_AUTH_SOCK` is populated correctly in both shells. Looking through an SSH connection log in WSL2, this is interesting, though:
`debug1: pubkey_prepare: ssh_get_authentication_socket: Connection refused`
I wonder if effective file permissions for the `/mnt`-based Windows drives are somehow slightly different

**Comment by mackncheesiest** [comment]
I wonder if WSL V2 currently has broken `AF_UNIX` support.

I ran the example code they provide [here](https://github.com/MicrosoftDocs/WSL/blob/live/wsl-samples/afunix-wsl-interop/linux/bind.c) with the socket created by `wsl-ssh-agent` as the `server_full_path` and it gave me `server bind error: Operation not supported`

While running the same code in my WSL V1 distro gives `binding to: '/mnt/c/path/to/sock.sock`

Edit: mileage may vary for others in the Windows Insider Program. I'm in the "slow track" and testing on `Win10 19033.1`. Can't say where "fast track" support is at

**Comment by aleksijohansson** [comment]
I just upgraded my Windows to the "fast track" and Ubuntu to WSL-2. Environment variables are there, but `ssh-add -l` gives `Error connecting to agent: Connection refused`. This wsl-ssh-agent project is so useful, thanks! I would like too see support for WSL-2.

Edit: I was trying WSL-2 to get rid of permission issues with Docker for Windows and they seemed to be even worse with WSL-2 at the moment so I switched back to WSL-1 for now.

**Comment by rupor-github** [comment]
I think most of the problems will be sorted as WSL2 nears the release - my understanding is that AF_UNIX sockets should simply work transparently.

**Comment by ldormoy** [comment]
I couldn't get it to work with WSL 2 either.

A good workaround is to start the linux ssh-agent from your ~/.bashrc or ~/.zshrc:
```
# SSH agent workaround
setopt +o nomatch
if [ -z "$(pgrep ssh-agent)" ]; then
        rm -rf /tmp/ssh-*
        eval $(ssh-agent -s) > /dev/null
else
        export SSH_AGENT_PID=$(pgrep ssh-agent)
        export SSH_AUTH_SOCK=$(find /tmp/ssh-* -name agent.*)
fi

# add ssh key to agent
if [ -z "$(ssh-add -l | fgrep $HOME/.ssh/id_rsa)" ]; then
        ssh-add ~/.ssh/id_rsa
fi
```

**Comment by aleksijohansson** [comment]
@ldormoy does this workaround work so that you don't have to put in your SSH keys passphrase every time you start WSL?

**Comment by ldormoy** [comment]
> 
> 
> @ldormoy does this workaround work so that you don't have to put in your SSH keys passphrase every time you start WSL?

You still have to enter it once every time you start Windows.

**Comment by DavidBoman** [comment]
I can confirm that this is still an issue with WSL 2.
I'm running WSL 2 from Slow ring. Current OS build is 19041.21.


maverick>  export | grep SSH_AUTH
declare -x SS>H_AUTH_SOCK="/mnt/c/Users/david/AppData/Local/Temp/ssh-650192815.sock"

maverick> file /mnt/c/Users/david/AppData/Local/Temp/ssh-650192815.sock
/mnt/c/Users/david/AppData/Local/Temp/ssh-650192815.sock: empty

maverick> ls -laF /mnt/c/Users/david/AppData/Local/Temp/ssh-650192815.sock
-rwxrwxrwx 1 root root 0 Feb  8 21:22 /mnt/c/Users/david/AppData/Local/Temp/ssh-650192815.sock*

 maverick> ssh-add -l
Error connecting to agent: Connection refused

**Comment by aleksijohansson** [comment]
WSL 2 from Slow ring. Current OS build number 19041.48. Still an issue.

**Comment by amnore** [comment]
For those using WSL 2, you might be interested in this one:
https://github.com/BlackReloaded/wsl2-ssh-pageant

**Comment by rupor-github** [comment]
Documentation added
