### ISSUE TITLE
wsl-ssh-agent-gui.exe complains of lack of ~/.gclpr directory even if gclpr is not being used

### ISSUE THREAD

**Issue by Viqsi** [rupor-github/wsl-ssh-agent#30]
Going from wsl-ssh-agent 1.5.2 to 1.6.0, suddenly the presence of gclpr seems to be enforced. With 1.5.2, I can just start it up with my environment and there's no problem. With 1.6.0, I get this error:

![image](https://user-images.githubusercontent.com/6570923/165350644-2b713632-6919-40f6-a8da-15310bd64c92.png)

If I create an empty .gclpr directory, both 1.5.2 and 1.6.0 report the same error (bad permissions on a nonexistent file in that directory), so this appears to be a regression.

**Comment by rupor-github** [comment]
Please, use release 1.6.1
