### ISSUE TITLE
Connection might not work after update to Ubuntu 22.04

### ISSUE THREAD

**Issue by AndreasGocht** [rupor-github/wsl-ssh-agent#31]
Dear all,

I recently had to update my Ubuntu to 22.04 due to various reasons. Unfortunately, this broke the ssh-agent interoperability. 

After a lot of research, it turned out, that there was a recent change in the agent communication, leading to errors like:
```
debug1: get_agent_identities: ssh_fetch_identitylist: communication with agent failed
```

The solution for me was to update my OpenSSH instance. This required disabling the built-in OpenSSH, and install the most recent version from https://github.com/PowerShell/Win32-OpenSSH/releases . After adding this OpenSSH version to the Windows PATH (e.g. by adding `%ProgramFiles%\OpenSSH\` ), everything works again as before.

Please note, that I am using WSL2 and `npiperelay` . But I assume that this will affect `wsl-ssh-agent` as well.

Best,

Andreas

**Comment by rupor-github** [comment]
This was discussed before, for example here: https://github.com/rupor-github/wsl-ssh-agent/issues/29 ...

**Comment by AndreasGocht** [comment]
Sorry, my fault.

Best,

Andreas
