### ISSUE TITLE
How to use correct key when I have multiple for github.com

### ISSUE THREAD

**Issue by jibbers42** [rupor-github/wsl-ssh-agent#32]
I use work key and a personal key on github and have my `.ssh\config` setup on the Windows side as described at https://gist.github.com/oanhnn/80a89405ab9023894df7. I'm sharing keys with WSL2 with the https://github.com/rupor-github/wsl-ssh-agent#wsl-2-compatibility technique.

Things work well on Windows:
```console
> ssh -T git@github.com
Hi jibbers42! You've successfully authenticated, but GitHub does not provide shell access.

> ssh -T git@github.com-work
Hi work! You've successfully authenticated, but GitHub does not provide shell access.
```

But on WSL2 it seems to select my work key for personal (github.com) and the work host (github.com-work) doesn't work at all:
```console
$ ssh -T git@github.com
Hi work! You've successfully authenticated, but GitHub does not provide shell access.

$ ssh -T git@github.com-work
ssh: Could not resolve hostname github.com-work: Name or service not known
```

My Windows `.ssh\config` is pretty simple:
```ssh-config
> cat .\.ssh\config
Host github.com
   HostName github.com
   IdentityFile ~/.ssh/jibbers42-ed25519
   IdentitiesOnly yes

Host github.com-work
   HostName github.com
   IdentityFile ~/.ssh/work-ed25519
   IdentitiesOnly yes
```

Any idea how I can get the WSL2 side to select the correct key?

**Comment by rupor-github** [comment]
This question is not related to `wsl-ssh-agent`... 

You did not put your keys into windows ssh-agent service (using `ssh-add`). Instead, you are reading them directly from files judging from your configuration `IdentityFile ~/.ssh/jibbers42-ed25519` and `IdentityFile ~/.ssh/work-ed25519`. As such `wsl-ssh-agent` has nothing to read from `ssh-agent` on windows end and make available on WSL2 side. 

This could be easily verified by issuing `ssh-add -L` on both Windows side and WSL2 side and comparing results.

**Comment by jibbers42** [comment]
I apologize for being off topic - I just hoped it was something someone here had experience with already since the WSL2 to Windows SSH agent would be out of experience for most people.

My thought was that the `IdentityFile ...` configuration told ssh which key to use, but it still used ssh-agent for credentials (I don't really know how it works). My keys have a passphrase that I am not prompted for so I'm sure I added them to ssh-agent and it's being used.

Both sides have the same `ssh-add -L` output...

Windows:
```console
> ssh-add -L
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK3E+1ehmyyQjfmDQ0a05L3jNvl+R3YskXZJCpPZxMGN work-ed25519
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAZHEf5lVMNMUFtOmlHKl76nOtCKY433nFqiNT22PE6m jibbers42-ed25519
```

WSL2:
```console
$ ssh-add -L
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK3E+1ehmyyQjfmDQ0a05L3jNvl+R3YskXZJCpPZxMGN work-ed25519
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAZHEf5lVMNMUFtOmlHKl76nOtCKY433nFqiNT22PE6m jibbers42-ed25519
```

**Comment by jibbers42** [comment]
For anyone else that runs into this, I copied my ssh keys and `.ssh\config` to the WSL2 side. Since the config uses tilde for paths, the same paths work from both Windows and WSL2 and didn't need to be fixed up in any way. Now the correct key is being used from both sides and ssh-agent on Windows is authenticating everything.

**Comment by rupor-github** [comment]
Agreed, this is as confusing as it could be... If you copied both keys and config - you may not need wsl-ssh-agent at all :) Not sure but in the future something like this: https://www.openssh.com/agent-restrict.html may be useful in such cases....
