### ISSUE TITLE
'Error connecting to agent' on one PC but working correctly on another with identical setup

### ISSUE THREAD

**Issue by MatejVitek** [rupor-github/wsl-ssh-agent#33]
I have two PCs, both running Windows 10, both with Ubuntu 20.04 installed in WSL 1. Both PCs start their OpenSSH Authentication service automatically on startup. Additionally on startup both run this program with the command:

    "C:\Program Files\WSL SSH Agent\wsl-ssh-agent-gui.exe" -setenv -envname WSL_AUTH_SOCK

Both of them also have the following two environment variables (I'm assuming automatically set by this program), identical, just with a different number in the temporary file name:
![image](https://user-images.githubusercontent.com/14276593/171254519-c0376a58-13c9-4e1d-b5f3-77e60eaf5db8.png)

In WSL I have the following line in `.bashrc` on both PCs:

    export SSH_AUTH_SOCK=$WSL_AUTH_SOCK

and nothing else agent-related in either `.bashrc` or `.profile`.

However, upon running Ubuntu, on one PC I can use the Windows SSH agent, and on the other I can't. Any idea what else I could try to get it working on the second PC?

## PC 1 (Working)
Powershell (outside WSL):

    PS C:\Users\User> ssh-add -L
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGdmx21Jrea+X7XlvqNc49d+M59SXi/Elia0Sm9yJ4F9 User-PC

WSL:

    user@User-PC:~/repo$ echo $WSL_AUTH_SOCK
    /mnt/c/Users/User/AppData/Local/Temp/ssh-055412939.sock
    user@User-PC:~/repo$ ssh-add -L
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGdmx21Jrea+X7XlvqNc49d+M59SXi/Elia0Sm9yJ4F9 User-PC
    user@User-PC~/repo$ git pull
    Already up to date.

## PC 2 (Not working)
Powershell (outside WSL):

    PS C:\Users\user> ssh-add -L
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP69b6DhaQqgKVZWNnhbSbhBXG1OH3yePiAHfdyTU+f1 user@PC

WSL:

    user@PC:~/repo$ echo $WSL_AUTH_SOCK
    /mnt/c/Users/user/AppData/Local/Temp/ssh-921384019.sock
    user@PC:~/repo$ ssh-add -L
    Error connecting to agent: No such file or directory
    user@PC:~/repo$ git pull
    git@github.com: Permission denied (publickey).
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.

**Comment by rupor-github** [comment]
You could add "debug" switch and use DbgView to see program produce verbose output - this may provide some additional information.

**Comment by MatejVitek** [comment]
Running the program with `-debug` once seems to have fixed the problem. I'm not sure why this would  be the case but the same thing happened on my laptop, where it wasn't working, even after several reboots, but after running once with the `-debug` switch, it's now working normally. I suppose this is resolved.
