### ISSUE TITLE
WSL2 and Windows 11 ssh not working

### ISSUE THREAD

**Issue by headler** [rupor-github/wsl-ssh-agent#35]
Hello,
I'm running debian 11 in WSL2 on Windows 11 host,
Every time when i'm trying to use `ssh` with wsl-ssh-agent i'm getting an error like:
`debug1: get_agent_identities: ssh_get_authentication_socket: No such file or directory`

This occurs only for ssh commands, `ssh-add -L` (and `-l`) works well - it returns all keys available in the agent.
I've already double checked SSH versions:
Debian:
```ssh -V
OpenSSH_8.9p1, OpenSSL 1.1.1n  15 Mar 2022
```
Windows:
```ssh -V
OpenSSH_for_Windows_8.9p1, LibreSSL 3.4.3
```

How to troubleshoot this?

Thank you

**Comment by rupor-github** [comment]
Please, read the readme - you are specifically interested in section called "WSL 2 compatibility". I am not sure where your `ssh-add` gets a list of identities really - looks like you have ssh-agent local to your WSL2 distro running and managed to add your keys there. I am mostly maintaining this program for legacy reasons - it was created at the time of WSL1 when Unix socket interop was working.

**Comment by headler** [comment]
Thanks for the quick reply, 
I don't have any locally running ssh-agents - if i try to use `ssh-add -l` it's showing a proper key added (without local ref file) to the agent:
```
ssh-add -l
2048 SHA256:qJiJXRM6V5l9pr5gLu9vFW+Cg2f1CStKJk2Gumywsgo  (RSA)
```

The error (in first message) from `ssh -v` is saying that socket file isn't available, but i'm sure permissions is OK and it's available for ssh-add. So i'm looking for a ways to troubleshoot it.. Wasn't able to find any other suitable ways to use ssh-agent in WSL2 :|

Thank you

**Comment by rupor-github** [comment]
To use Windows side ssh-agent in WSL2 distro you do not need this program. Instead, you need to bridge Windows named pipe on Windows side and Unix socket on WSL2 side. Readme has an example how to do it. If you need help with this part - please, show exactly what you did to make it happen. From your messages I could see that staff does not work, but I cannot understand what you did to make it work, sorry.

**Comment by headler** [comment]
Well, sorry for disturbance, but it seems the error is caused by the program i'm using in first place - keepass + keeagent plugin.
https://github.com/dlech/KeeAgent/issues/341

I'll investigate this further, thank you for your answers!
