### ISSUE TITLE
[Docs] Put `npiperelay.exe` onto Windows filesystem to fix delays

### ISSUE THREAD

**Issue by strarsis** [rupor-github/wsl-ssh-agent#40]
It may have been the case that `npiperelay.exe` had to be put onto the `devfs` filesystem in order to be usable at all, 
but this is not necessary anymore and it introduces significant delays. 
Putting it onto the Windows filesystem fixes the delay issues.
https://github.com/rupor-github/wsl-ssh-agent#wsl2-compatibility:~:text=on%20devfs%20for%20interop

**Comment by rupor-github** [comment]
It should read "drvfs" as followup example suggests. Thank You, I fixed readme file.
