### ISSUE TITLE
[Question] `npiperelay.exe` build

### ISSUE THREAD

**Issue by strarsis** [rupor-github/wsl-ssh-agent#41]
The releases of this project come with the `npiperelay.exe` binary already included, which is very helpful.
Should this be the same `npiperelay.exe` as from the upstream [`npiperelay` repository](https://github.com/jstarks/npiperelay), 
or were adjustments necessary to make it work more smoothly?

**Comment by rupor-github** [comment]
No changes were made to the npiperelay for this project.

**Comment by strarsis** [comment]
Thanks! So the `npiperelay.exe` [`v0.1.0`](https://github.com/jstarks/npiperelay/releases/tag/v0.1.0) would be the same version?

**Comment by rupor-github** [comment]
<img width="999" alt="image" src="https://user-images.githubusercontent.com/5368784/222960006-4696ef01-00ec-404d-a91c-2261268ce78d.png">
