### ISSUE TITLE
WSL2 won't get keys despite agent has em

### ISSUE THREAD

**Issue by mircsicz** [rupor-github/wsl-ssh-agent#42]
Thank you very much for this awesome Project but I'm afraid I need to ask for help:
After fideling with this for some hours, where I wasted the first few as I thought I could simply transfer from WSL1... :-(

When I try to connect to a host like that: "ssh -i .ssh/mykey myhost -vvv" I see this:
```
debug3: ssh_get_authentication_socket_path: path '/home/mircsicz/.ssh/wsl-ssh-agent.sock'
debug2: get_agent_identities: ssh_agent_bind_hostkey: communication with agent failed
debug1: get_agent_identities: ssh_fetch_identitylist: communication with agent failed
```
and it asks for the passwd to the key but it's there:

```
ssh-add -l
4096 SHA256:string mykey (RSA)
```

I've wsl-ssh-agent-relay in place (~/bin/wsl-ssh-agent-relay) also changed "RELAY_BIN="${HOME}/bin/npiperelay.exe" and an entry in my .bashrc:
```
${HOME}/bin/wsl-ssh-agent-relay start
export SSH_AUTH_SOCK=${HOME}/.ssh/wsl-ssh-agent.sock
```
And yes it's def WSL2:
```
C:\Users\mircsicz>wsl.exe -l --all -v
  NAME          STATE           VERSION
- kali-linux    Running         2
```

But now I'm totally out of ideas!

**Comment by mircsicz** [comment]
Also I just tried 
```
└─$ bin/wsl-ssh-agent-relay -v foreground
WSL has been shutdown ungracefully, leaving garbage behind
Relay is running with PID: 37
Polling remote ssh-agent...OK
Entering wait...
```

**Comment by rupor-github** [comment]
The only thing which comes to mind quickly: what version of OpenSSH are you running on Windows side? I am not familiar with kali but there were some protocol changes in ssh protocol recently and later distros often request keys in a way which OpenSSH distributed with Windows simply does not support.

Aso, please, make sure that your distro is not running Linux side ssh-agent...

**Comment by rupor-github** [comment]
What is the `debug1: Will attempt key: ` in your debug output shows? What keys? I really do not understand why you need to choose particular identity on the command line: `ssh -i .ssh/mykey myhos` if you want to use ssh-agent provided key. All identities available in ssh-agent should be offered by your ssh client without any additional CLI options, using `-i` prohibits this if I am mot mistaken...

**Comment by mircsicz** [comment]
> What is the `debug1: Will attempt key: ` in your debug output shows? 

There's no such output, at least none that contains: "Will attempt key:" ...

> What keys? I really do not understand why you need to choose particular identity on the command line: `ssh -i .ssh/mykey myhos` if you want to use ssh-agent provided key. All identities available in ssh-agent should be offered by your ssh client without any additional CLI options, using `-i` prohibits this if I am mot mistaken...

That is just a replacement for my .ssh/config entry:
```
host myhost
  hostname xxx.yy.z.60
  User mircsicz
  Compression yes
  Port 22
  ForwardAgent no
  IdentityFile ~/.ssh/mykey
```

**Comment by rupor-github** [comment]
I may be totally off here - but if ssh-agent has your key - you do not need `IdentityFile ~/.ssh/mykey` or `-i ~/.ssh/mykey` or what would be the point of sharing the identity with WSL2 host really? I have something like this in my config:

```
host myhost
  hostname xxx.yy.z.60
  User mircsicz
```

and I do `ssh myhost` and that is enough for it to work (if `ssh-add -L` shows right keys)

**Comment by mircsicz** [comment]
That failes if you have more than five (or so) keys in the agent. There’s an sshd_config param called „MaxAuthTries“ …

**Comment by rupor-github** [comment]
You may want to use IdentitiesOnly to overcome `too much login attempts`, but it is a strange idea in general to have signatures for all your keys broadcast every time you are trying to connect to some server. Key is supposed to represent a client and multiple clients need to be registered on the server, not the other way around. I do not think specifying identity with -i is going to help you here at all, but there are some recent protocol extensions (experimental) which allow you to configure what key to send for what server: https://www.openssh.com/agent-restrict.html
