### ISSUE TITLE
Problem with wsl2 and systemd

### ISSUE THREAD

**Issue by rkl110** [rupor-github/wsl-ssh-agent#45]
if you have issus in using [wsl-ssh-agent-relay](https://github.com/rupor-github/wsl-ssh-agent/blob/master/docs/wsl-ssh-agent-relay) with systemd try adding `:WSLInterop:M::MZ::/init:PF` to `/usr/lib/binfmt.d/WSLInterop.conf`.

```bash
sudo sh -c 'echo :WSLInterop:M::MZ::/init:PF > /usr/lib/binfmt.d/WSLInterop.conf'
```

[Microsoft/WSL - Issue 8843](https://github.com/microsoft/WSL/issues/8843)

**Comment by rupor-github** [comment]
Thank You - I'll add this to readme!
