### ISSUE TITLE
`wsl-ssh-agent-relay` relies on systemd

### ISSUE THREAD

**Issue by Cynosphere** [rupor-github/wsl-ssh-agent#46]
My main WSL distro is Void Linux (via [VoidWSL](https://github.com/am11/VoidWSL)) which does not use systemd. Would it be possible to make `wsl-ssh-agent-relay` not rely on `start-stop-daemon`?

**Comment by rupor-github** [comment]
It is totally possible to write some script which will do what 'wsl-ssh-agent-relay' does without using any tools. I am unfamiliar with Void Linux, so I cannot help you with this one. Just find out what is the best way of running background task on startup in Void and put properly prepared `socat UNIX-LISTEN:"\"${WSL_AGENT_SSH_SOCK}\"",fork EXEC:"\"\'${RELAY_BIN}\' -ei -s \'//./pipe/openssh-ssh-agent\'\"",nofork 1>/dev/null 2>&1 &` in the script - you should be fine then. `wsl-ssh-agent-relay` is provided as an example how to do that and works fine on every distro I am using with or without systemd so far.
