### ISSUE TITLE
Following Instruction for npiperelay results in invalid ELF header

### ISSUE THREAD

**Issue by arcsector** [rupor-github/wsl-ssh-agent#47]
I am trying to get pageant working with WSL2 on windows 10 build 1903 - I'm mainly stuck on the part where the SSH agent opens the DLL for pageant to prompt for authentication, my pageant certificate is a dll, and when WSL2 tries to open that, it fails with this message:

```
dlopen /mnt/c/Program Files/Package/acpkcs211.dll failed: /mnt/c/Program Files/Package/acpkcs211.dll: invalid ELF header
```

I'm unsure where this is failing, at the Npiperelay, or the ssh agent, so I thought I'd start here. Thanks for the help, and I hope this gets other people to a closer solution.

**Comment by rupor-github** [comment]
I am a bit confused - this project has nothing to do with pegeant, which as far as I could remember (it was long time ago) is using memory sharing and somewhat Putty specific certificate storage. May be you are looking for https://github.com/benpye/wsl-ssh-pageant ?

**Comment by arcsector** [comment]
My bad, I thought this would work in tangent with the pageant fix - thanks and sorry for the confusion.
