### ISSUE TITLE
`-setenv` by default

### ISSUE THREAD

**Issue by lusitania** [rupor-github/wsl-ssh-agent#5]
Please enable this option by default. Currently the variable SSH_AUTH_SOCK (or its override) is not present within the WSL environment without setting the option. From what I understand however this is the intended purpose of `wsl-ssh-agent-gui.exe`. IMO having an option `-nosetenv` is more reasonable, if needed at all.

**Comment by rupor-github** [comment]
It may be unfortunate that I did not think about it to begin with, however changing semantics after release seems a bit harsh to me. Specifying an option however seems very easy. Also at the moment `-setenv` has some explained (issue #2) and unexplained (issue #1) phenomena associated with it  - so unless I could reproduce and fully understand what is going on in #1 - I would be reluctant to consider what you are proposing, sorry.

**Comment by shawnz** [comment]
The advantage to having this option as default is that the application can be run just by double clicking or creating a shortcut in the startup folder with no command line at all. Currently it is necessary to specify a command line to be able to use the application (in practice).

Those who do not want to use the "setenv" option are forced to specify a command line anyway, so there's no detriment to them (except maybe having to change their configs after such a change.. and only if they suffer from issue #1 which is not universal)

#2 could be resolved by changing the default env name to WSL_AUTH_SOCK.

**Comment by rupor-github** [comment]
@shawnz - Issue #1 has been fully resolved, I am still a bit hesitant to change what is already there as you are proposing 2 changes (which totally make sense by the way): change default environment variable name and replace --setenv with --nosetenv. And then start answering questions from people who downloaded new version and did not read readme :). I will give it some additional thought...

**Comment by shawnz** [comment]
Understandable, and regardless thank you anyway for this project. It has been very helpful for me.
