### ISSUE TITLE
Connection refused when connecting through IntelliJ IDEA terminal set as WSL

### ISSUE THREAD

**Issue by sandrinr** [rupor-github/wsl-ssh-agent#6]
I have setup `wsl-ssh-agent-gui` to be started with the `-setenv` option and in WSL I ensure the `SSH_AUTH_SOCK` env var is set.

When I try to list my SSH identities on a WSL terminal provided by IntelliJ IDEA (by using the terminal startup command `wsl -d Ubuntu` I get `Error connecting to agent: Connection refused`.

When I try the same in a Ubuntu shell (or by manually starting the Ubuntu shell by using `wsl -d Ubuntu` in `cmd`) I get my identities listed as expected.

Is there some checking going on about where these connections to the agent are coming from which might prevent connections not originating from the "original WSL shell"?

**Comment by rupor-github** [comment]
Looks like IDEA is using Windows OpenSSH tools and you have a conflict. Form the README:

> NOTE: Setting SSH_AUTH_SOCK environment on Windows side may (and probably will) interfere with some of Windows OpenSSH. As far as I could see presently utilities in Windows\System32\OpenSSH expect this environment variable to be either empty or set to proper ssh-agent.exe pipe, otherwise they cannot read socket.

Workaround is also described in README: 
> To avoid this and still be able to use -setenv and automatically generated socket path use -envname to specify variable name to set. Later on WSL side you could use:
`export SSH_AUTH_SOCK=${<<YOUR-NAME-HERE>>}`

**Comment by sandrinr** [comment]
Thank you for the input, however, I don't think this is the issue here.

(1) I am already using the startup command: `wsl-ssh-agent-gui.exe" -setenv -envname=WSL_SSH_AUTH_SOCK` and in Ubuntu I am setting the `SSH_AUTH_SOCK` using `[ -n ${WSL_SSL_AUTH_SOCK} ] && export SSH_AUTH_SOCK=${WSL_SSH_AUTH_SOCK}`. I am not setting `SSH_AUTH_SOCK` on the windows side (and it is indeed not set, when checking for example in PowerShell).

(2) In this case I don't think it is relevant what IDEA uses as an SSH client. We are only talking about the embedded terminal here. The terminal actually runs the exact same shell command as the Ubuntu terminal does (`wsl.exe -d Ubuntu`). `which ssh` returns `/usr/bin/ssh` inside the IDEA terminal.

**Comment by rupor-github** [comment]
When IDEA embedded terminal is open could you verify what your SSH_AUTH_SOCK points to? Is it possible that you started IDEA before starting wsl-ssh-agent-gui.exe? Because embedded terminal being a child process of IDEA will surely inherit old environment variables...

**Comment by sandrinr** [comment]
Sure.
```
<WSL>$ echo $SSH_AUTH_SOCK
/mnt/c/Users/<user>/AppData/Local/Temp/ssh-023246071.sock
``` 
It is the same as in a "normal" WSL terminal.

**Comment by rupor-github** [comment]
I really do not understand what command refuses to connect - which part of the system gives you  error message? Simply starting embedded terminal in IntelliJ just works:

![Clipboard01](https://user-images.githubusercontent.com/5368784/65896651-99a94280-e37b-11e9-8601-bff56c3da285.jpg)

**Comment by cHolzberger** [comment]
Hey, i am experiencing the same problem when trying to use it from wsl2, wsl1 works fine

**Comment by rupor-github** [comment]
There is issue #3 discussing WSL 2  compatibility. I have no way of checking that (until WSL 2 is actually released) and no resources to support unreleased Microsoft products 😄

**Comment by sandrinr** [comment]
@rupor-github You are probably right, that this is not caused by wsl-ssh-agent. However, since you got it working with IDEA I would be interested to know which shell you are using, i.e. what have you set in `Settings->Tools->Terminal->Shell path`. I've set `C:\Windows\System32\bash.exe` there.

**Comment by rupor-github** [comment]
@sandrinr I had to install InelliJ trying to reproduce the issue - I am not really using it. I tried 3 things:
1. default settings (cmd) then typed `wsl -d WLinux`, then `ssh-add -l`
2. set `wsl` in shell path then did  `ssh-add -l`
3. set `"c:\windows\system32\wsl.exe" -d WLinux` in shell path, then did  `ssh-add -l`

All 3 behaved exactly the same way 😄 

My understanding was that `bash.exe` has been deprecated for a while.

**Comment by ethanbb** [comment]
I have this issue with WSL 1 (and PyCharm rather than IntelliJ). However, for me, the `WSL_AUTH_SOCK` and `SSH_AUTH_SOCK` variables refer to a different socket than I see in a standalone WSL terminal, in cmd.exe, or in the system environment variable editor. It's another socket in the same directory (`AppData/Local/Temp`) but with a different number.

It works if I start PyCharm from a cmd window. This might be an issue with how JetBrains products deal with environment variables, but I'm not sure how to look into that.
