### ISSUE TITLE
Gracefully stop wsl-ssh-agent-gui from command line

### ISSUE THREAD

**Issue by kai2nenobu** [rupor-github/wsl-ssh-agent#7]
I'm creating a [chocolatey](https://chocolatey.org/) package for wsl-ssh-agent ([package source](https://github.com/kai2nenobu/chocolatey_packages/tree/add_wsl-ssh-agent_package/wsl-ssh-agent)).  I want to gracefully stop `wsl-ssh-agent-gui` process before updating wsl-ssh-agent package.

When I forcibly stop `wsl-ssh-agent-gui` by powershell `Stop-Process` cmdlet, socket file and lock file generated by `wsl-ssh-agent-gui` (like `ssh-126447479.sock`, `wsl-ssh-agent-gui.lock`) remain in `%TEMP%` folder.

Is there a good method to gracefully stop `wsl-ssh-agent-gui` process from command line (`powershell` or `cmd`)?

**Comment by rupor-github** [comment]
Presently I do not think so - but I do not think you actually need it. "systray_temp_icon" file in tmp directory is not being cleaned anyways and .lock file will be safely overwritten next time program starts. So the only actual garbage you'd see could be .sock file. If this sock file has "well known" name - it will be overwritten next time program starts and if "default" name is used - it would leave a single 0 length file in tmp directory - no harm there. I would take a look if it is actually possible to intercept termination signal in gui app those days and do some additional cleanup, but I do not think this is critical for what you are doing.

**Comment by kai2nenobu** [comment]
Thanks to reply.
I'm glad to hear that garbage has no harm.

**Comment by Bnaya** [comment]
Where can i find this package? :)
Thanks!!

**Comment by kai2nenobu** [comment]
> Where can i find this package? :)
> Thanks!!

You can find a package [here](https://www.myget.org/feed/kai2nenobu/package/nuget/wsl-ssh-agent). See [README](https://github.com/kai2nenobu/my-chocolatey-packages/blob/master/README.md) fore more details.

This is an unofficial package (means not made by @rupor-github). So, if you find some problems about this package, post a issue in [package repository](https://github.com/kai2nenobu/my-chocolatey-packages/issues).
